arangodb:
  spring:
    data:
      hosts: localhost:8529
      user: root
      password: test123
      database: file-system-entries
file-locator:
  skip-paths: >-
    /mnt,
    /net,
    /tmp,
    /udev,
    /boot,
    /proc,
    /run
