arangodb:
  spring:
    data:
      hosts: arangodb:8529
      user: root
      password: test123
      database: file-entries

file-locator:
  nodes-collection: nodes
  edges-collection: edges
  graph-name: fileSystemGraph
  skip-paths: >-
    /afs,
    /dev,
    /media,
    /mnt,
    /net,
    /sfs,
    /tmp,
    /udev,
    /var/cache,
    /var/lib/pacman/local,
    /var/lock,
    /var/run,
    /var/spool,
    /var/tmp,
    /boot,
    /proc,
    /run

server:
  ssl:
    enabled: false
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always
  servlet:
    context-path: "/"
  port: 8080

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      enabled: true
      show-details: always

spring:
  application:
    name: file-locator

logging:
  level:
    root: info
